optimizers:
  trunk_optimizer:
    RMSprop:
      lr: 1.0e-06
      weight_decay: 0.0001
      momentum: 0.9
  embedder_optimizer:
    RMSprop:
      lr: 1.0e-06
      weight_decay: 0.0001
      momentum: 0.9
  metric_loss_optimizer:
    RMSprop:
      weight_decay: 0
      momentum: 0.9
      lr: 0.00011114005894862011
